### PR TITLE
[on hold] Added forced device selection to init_sd_card

### PR DESCRIPTION
**Pull request by AleksandarPetrov**
Sometimes Etcher doesn't show SD cards (especially in a VM). This workaround allows adding an extra parameter `--device` when calling `init_sd_card` that directly passes the device driver with the SD card to Etcher.

### CODE REVIEW

**Comment by AndreaCensi** [comment]
@AleksandarPetrov interesting work, but will not merge now because things are a bit unstable as they are

**Comment by AndreaCensi** [comment]
@AleksandarPetrov we should do the equivalent for init_sd_card2

**Comment by AleksandarPetrov** [comment]
Which one? Just the extra `--drive` parameter or the complete dockerization of the process?

**Comment by AndreaCensi** [comment]
@AleksandarPetrov I started the work on branch `etcher` but cannot finish / test now.
Have a go?
It's an adaptation of your code.

**Comment by AleksandarPetrov** [comment]
Will try to give it a try it tonight!

**Pull request closed without merging**
