### PR TITLE
adding a default directory to put logs in

### PR DESCRIPTION
**Pull request by liampaull**

### CODE REVIEW

**Comment by AndreaCensi** [comment]
will fail if the user is not root and `media` does not exist.

Suggest `os.path.expanduser("~/logs")`.

**Comment by liampaull** [comment]
@AndreaCensi would it make sense to put the collected logs in `/data/logs` ? 
I find the passing of the volume in docker to /home/user kind of clunky because usernames could be different unless you can think of a workaround ?

**Comment by AndreaCensi** [comment]
Again, `/data/logs` would not be writable.

For passing the dir, yes, do something like:

```
-v $HOME/logs:/data/logs
```

**Comment by liampaull** [comment]
I don't understand how it's not writable if the calibration commands are doing exactly the same thing. Bonus this way is that the logs are available through the web interface.

**Comment by liampaull** [comment]
by the way I tested this method for passing volume and with -H hostname.local it doesn't work (since the env var does not evaluate correctly)

**Pull request closed without merging**
