### PR TITLE
Daffy demo patch

### PR DESCRIPTION
**Pull request by kochaika**
@afdaniele -- I check it
This PR fixes an issue `requests.exceptions.ConnectionError: HTTPConnectionPool(host='autobot06', port=2375):...`

### CODE REVIEW

**Comment by kochaika** [comment]
kot@kot-ThinkPad-T14s:~/Downloads$ dts duckiebot demo --debug --demo_name lane_following --duckiebot_name autobot06 --package_name duckietown_demos
                                                                                                         
dts :  Problems with a command?                                                                          
    :                                                                                                    
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :                                                                                                    
    :      Troubleshooting:                                                                              
    :                                                                                                    
    :      - If some commands update fail, delete ~/.dt-shell/commands           
    :                                                                                                    
    :      - To reset the shell to "factory settings", delete ~/.dt-shell          
    :                                                                                                    
    :        (Note: you will have to re-configure.)                                                      
INFO:dts:Commands version: daffy-demo-patch                                                              
INFO:dts:looking at /home/kot/.dt-shell/commands-multi/daffy-demo-patch                                  
INFO:dts:Target architecture automatically set to arm32v7.                              
INFO:dts:Using package duckietown_demos                                                                  
**ping: autobot06.local.local: Name or service not known                                                   
Unable to locate autobot06.local.local!** 


But now I see this strange strings: autobot06.local.local

**Comment by afdaniele** [comment]
@pro100kot can you test it again? I pushed a fix

**Comment by kochaika** [comment]
@afdaniele in this branch?

**Comment by afdaniele** [comment]
@pro100kot yes

**Pull request merged**
